### ISSUE TITLE
AssertionError: Result length not requested length

### ISSUE THREAD

**Issue by noman55** [julien-duponchelle/python-mysql-replication#474]
I am using  'mysql-replication==0.25'
pymysql version 'pymysql==0.9.3',
MySQL RDS version = 5.7
Still getting the error
AssertionError: Result length not requested length:
Expected=2958. Actual=30. Position: 64250. Data Length: 64280

```
Traceback (most recent call last):

File "/usr/local/lib/python3.7/site-packages/tap_mysql/lib/streamer.py", line 173, in _extract_records

for row in binlog_event.rows:

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/row_event.py", line 443, in rows

self._fetch_rows()

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/row_event.py", line 438, in _fetch_rows

self.__rows.append(self._fetch_one_row())

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/row_event.py", line 491, in _fetch_one_row

row["values"] = self._read_column_data(self.columns_present_bitmap)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/row_event.py", line 191, in _read_column_data

values[name] = self.packet.read_binary_json(column.length_size)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 350, in read_binary_json

return self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type

return self.read_binary_json_object(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 438, in read_binary_json_object

data = self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type

return self.read_binary_json_object(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 438, in read_binary_json_object

data = self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type

return self.read_binary_json_object(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 438, in read_binary_json_object

data = self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type

return self.read_binary_json_object(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 438, in read_binary_json_object

data = self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type

return self.read_binary_json_object(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 438, in read_binary_json_object

data = self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 357, in read_binary_json_type

return self.read_binary_json_array(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 463, in read_binary_json_array

return [_read(x) for x in values_type_offset_inline]

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 463, in <listcomp>

return [_read(x) for x in values_type_offset_inline]

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 461, in _read

return self.read_binary_json_type(x[0], length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type

return self.read_binary_json_object(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 438, in read_binary_json_object

data = self.read_binary_json_type(t, length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 357, in read_binary_json_type

return self.read_binary_json_array(length - 1, large)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 463, in read_binary_json_array

return [_read(x) for x in values_type_offset_inline]

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 463, in <listcomp>

return [_read(x) for x in values_type_offset_inline]

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 461, in _read

return self.read_binary_json_type(x[0], length)

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 355, in read_binary_json_type



return self.read_binary_json_object(length - 1, large)=

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 430, in read_binary_json_object

Copy
keys = [self.read(x[1]) for x in key_offset_lengths]

File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 430, in <listcomp>

keys = [self.read(x[1]) for x in key_offset_lengths]



File "/usr/local/lib/python3.7/site-packages/pymysqlreplication/packet.py", line 150, in read

return data + self.packet.read(size - len(data))

File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 73, in read

raise AssertionError(error)

AssertionError: Result length not requested length:


Expected=2958. Actual=30. Position: 64250. Data Length: 64280

```

**Comment by sean-k1** [comment]
@noman55 hello let me know Binary Log Formats value
and Please let me know how I can reproduce this issue.

[refer this page](https://mariadb.com/kb/en/json-data-type/#replicating-json-data-between-mysql-and-mariadb)

content 

Replicating JSON Data Between MySQL and MariaDB
The JSON type in MySQL stores the JSON object in a compact form, not as [LONGTEXT](https://mariadb.com/kb/en/longtext/) as in MariaDB. This means that row based replication will not work for JSON types from MySQL to MariaDB.

There are a a few different ways to solve this:

Use statement based replication.
Change the JSON column to type TEXT in MySQL
If you must use row-based replication and cannot change the MySQL master from JSON to TEXT, you can try to introduce an intermediate MySQL slave and change the column type from JSON to TEXT on it. Then you replicate from this intermediate slave to MariaDB.

**Comment by abdullahmafuz2020** [comment]
@sean-k1 
you can reproduce a similar issue if you run the below steps.
DB setting 
1. MySQL V 8.0.31
2. binlog_format = ROW

```sql
CREATE TABLE setting_table
(
    id SERIAL AUTO_INCREMENT,
    setting JSON
)
SELECT * FROM setting_table;
INSERT INTO setting_table (setting) VALUES ('{"btn": true, "model": false}');

UPDATE setting_table
        SET setting = JSON_REMOVE(setting, '$.model')
       WHERE id=1;
```

``` bash
Traceback (most recent call last):
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/app.py", line 129, in <module>
    main()
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/app.py", line 98, in main
    for row in binlogevent.rows:
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/row_event.py", line 480, in rows
    self._fetch_rows()
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/row_event.py", line 475, in _fetch_rows
    self.__rows.append(self._fetch_one_row())
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/row_event.py", line 564, in _fetch_one_row
    row["before_values"] = self._read_column_data(self.columns_present_bitmap)
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/row_event.py", line 115, in _read_column_data
    values[name] = self.__read_values_name(column, null_bitmap, null_bitmap_index,
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/row_event.py", line 231, in __read_values_name
    return self.packet.read_binary_json(column.length_size)
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/packet.py", line 368, in read_binary_json
    payload = self.read(length)
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysqlreplication/packet.py", line 170, in read
    return self.packet.read(size)
  File "/opt/miniconda3/lib/python3.10/site-packages/pymysql/protocol.py", line 74, in read
    raise AssertionError(error)
AssertionError: Result length not requested length:
Expected=1567384932.  Actual=3.  Position: 114.  Data Length: 117

```

**Comment by sean-k1** [comment]
@abdullahmafuz2020 I'm pretty not sure This Pr resolve this Issue
Can you check this Issue in this [PR](https://github.com/julien-duponchelle/python-mysql-replication/pull/481)?

**Comment by abdullahmafuz2020** [comment]
@sean-k1 
after enabling "BINLOG_ROW_METADATA = FULL" 
I have tested [bug fix json Parser](https://github.com/julien-duponchelle/python-mysql-replication/pull/481) PR locally in MYSQL DB, and it's working fine.
tried a few different test cases, and all seem working !!!🎉

`couldn't test on the production database where the actual issue was raised because it required "BINLOG_ROW_METADATA = FULL" to be enabled. To enable metadata setting in prod, it will take some days and to test on a production database.`
> will test in production and get back to you in a week.

Anyway 
Thanks so much for your effort to fix this bug

**Comment by sean-k1** [comment]
@abdullahmafuz2020 Thanks!

**Comment by abdullahmafuz2020** [comment]
hey @sean-k1 
I deployed bug fix json parser code from your PR.
it worked for 10 hours then the below error popped up 
it happened in nested JSON 
`{"information": {"purpose": null, "Number": null, "Status": null}}`

```bash
Traceback (most recent call last):
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/app.py", line 137, in <module>
    main()
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/app.py", line 103, in main
    for row in binlogevent.rows:
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/row_event.py", line 492, in rows
    self._fetch_rows()
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/row_event.py", line 487, in _fetch_rows
    self.__rows.append(self._fetch_one_row())
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/row_event.py", line 578, in _fetch_one_row
    row["before_values"] = self._read_column_data(self.columns_present_bitmap)
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/row_event.py", line 121, in _read_column_data
    values[name] = self.__read_values_name(
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/row_event.py", line 230, in __read_values_name
    return self.packet.read_binary_json(column.length_size)
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/packet.py", line 382, in read_binary_json
    value = self.read_binary_json_type(t, length)
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/packet.py", line 390, in read_binary_json_type
    return self.read_binary_json_object(length - 1, large)
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/packet.py", line 487, in read_binary_json_object
    data = self.read_binary_json_type(t, length)
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/packet.py", line 390, in read_binary_json_type
    return self.read_binary_json_object(length - 1, large)
  File "/Users/abdullahmohammed/Abdullah/local/sub-folder/util/lazarus_debug_script_mysql_short/pythonmysqlreplication/pymysqlreplication/packet.py", line 450, in read_binary_json_object
    raise ValueError("Json length is larger than packet length")
ValueError: Json length is larger than packet length
```

**Comment by sean-k1** [comment]
@abdullahmafuz2020 Did you run pull to this update branch ?
Does it error When update?

```
=== WriteRowsEvent ===
Date: 2023-09-23T07:34:19
Log position: 1593
Event size: 88
Read bytes: 12
Table: pymysqlreplication_test.json_test
Affected columns: 2
Changed rows: 1
Column Name Information Flag: True
Values:
--
* id : 2
* json_data : {b'information': {b'Number': None, b'Status': None, b'purpose': None}}
```

**Comment by abdullahmafuz2020** [comment]
@sean-k1 
no, I haven't taken the recent update code from your branch, I think 3 days old code 

meanwhile, take your recent code and run from `log_pos` it failed, and the error didn't rise and worked fine 
thanks for the update 
will deploy new changes in prod.

**Comment by abdullahmafuz2020** [comment]
hey @sean-k1 
no, I haven't taken the recent update code from your branch, I think 3 days old code 
meanwhile, take your recent code and run it
they some issues, I am facing 
`("{'schema': 'main_table', 'table': 'job_batches', 'binlog_timestamp': "
 "1695416511, 'fields': {None: None}, 'type': 'update'}")'

not working as expected, missing fields
but if I run using a 3-day old code, fields get proper data.

**Comment by sean-k1** [comment]
@abdullahmafuz2020 I think Setting is not Problem.
because 3days code goes properly.
Can you let me know Your simple Testcase?

**Comment by abdullahmafuz2020** [comment]
@sean-k1 
I didn't run any specific test case, I connected the prod replica database directly to the test branch code keeping the `log_file` and `log_pos` hard coding locally

**Comment by sean-k1** [comment]
@abdullahmafuz2020

Let me summarize my understanding
Based on the PR code I wrote 3 days ago, when you run  BinlogFile ("{'schema': 'main_table', 'table': 'job_batches', 'binlog_timestamp': " "1695416511, 'fields': {None: None}, 'type': 'update'}")' 
Here, the value of fields is not None, but it is filled with a value, and when you ran the latest PR code, it came out as None, right?

I don't think it's a problem with the BinlogStreamReader settings, it works fine with the same settings as yours, so I think the code I wrote is in error.

So ("{'schema': 'main_table', 'table': 'job_batches', 'binlog_timestamp': " "1695416511, 'fields': {None: None}, 'type': 'update'}")' I was asking about how to reproduce what might be causing the error in your Prod environment BinlogEvent.
Correct me if I understand something wrong!

**Comment by abdullahmafuz2020** [comment]
yes , you understood right 
I was working on reproducing locally.
with recent PR changes, it's happening with any event, update, insert 

using setting_table refer above on previous DDL  
```sql
INSERT INTO db.setting_table (setting) VALUES ('{"btn": true, "model": false}');
```

new code result
```python
{'schema': 'db', 'table': 'setting_table', 'binlog_timestamp': 1695472221, "
 "'fields': {None: {b'btn': True, b'model': False}}, 'type': 'insert'}
{'schema': 'db', 'table': 'setting_table', 'binlog_timestamp': 1695472345, "
 "'fields': {None: {b'btn': False, b'model': False}}, 'type': 'update'}
{'schema': 'db', 'table': 'setting_table', 'binlog_timestamp': 1695472398, "
 "'fields': {None: {b'btn': True, b'model': False}}, 'type': 'delete'}
```


3 day ago code result
```python
{'schema': 'db', 'table': 'setting_table', 'binlog_timestamp': 1695472221, "
 "'fields': {'id': 24, 'setting': {b'btn': True, b'model': False}}, 'type': "
 "'insert'}
{'schema': 'db', 'table': 'setting_table', 'binlog_timestamp': 1695472345, "
 "'fields': {None: {b'btn': False, b'model': False}}, 'type': 'update'}
{'schema': 'db', 'table': 'setting_table', 'binlog_timestamp': 1695472398, "
 "'fields': {None: {b'btn': True, b'model': False}}, 'type': 'delete'}
```

**Comment by abdullahmafuz2020** [comment]
@sean-k1 I updated the code result, I missed the place result as was running 2 codes in 2 different terminals.😕
please have a result again

**Comment by sean-k1** [comment]
@abdullahmafuz2020 so sorry can you run latest pr branch
I'm missing something while merging a conflicted branch

**Comment by abdullahmafuz2020** [comment]
seems working fine now 🚀 and `Json length is larger than packet length` issue is not coming so far
will deploy this branch in prod, and will update here if any issue pops up
thanks @sean-k1

**Comment by noman55** [comment]
Hi @abdullahmafuz2020 @sean-k1 Let me also deploy and test it. Sorry was occupied with something else couldn't get back  earlier. Just to be sure I need to deploy from this PR branch right? https://github.com/julien-duponchelle/python-mysql-replication/pull/481/files

**Comment by abdullahmafuz2020** [comment]
yes @noman55

**Comment by sean-k1** [comment]
@noman55 yes but some partial_update is not supported and time,timestamp is still develop now 

Remind this one

**Comment by sean-k1** [comment]
@noman55 oh your mysqlserver is 5.7 I think Column name is None..

**Comment by sean-k1** [comment]
@noman55 @abdullahmafuz2020 I develop time, timestamp 
but i said If you update json property UpdateEvent Cannot find.

We would love to develop a PARTIAL_UPDATE_ROW_EVENT right away, but it will take some time to implement it.
Hope you understand.

If you don't get it from the changed data in the json update, but just know that a partial update occurred, I'll add it to the PR.

**Comment by abdullahmafuz2020** [comment]
@sean-k1 thanks for letting us know.

**Comment by sean-k1** [comment]
@abdullahmafuz2020 we merged this pr on main branch!
check this out 
I fixed when long string cases too.
I hope this PR helps

**Comment by sean-k1** [comment]
@noman55  we release 0.45.0 version  for Mysql 5.7 Users
I think this version resolved this Issue!

**Comment by noman55** [comment]
@sean-k1 I am getting the same error for MySQL8.7 version
```
  'mysql-replication==0.25',
  'pymysql==0.9.3'
```
Can you guide what version I should use to resolve this issue? Thanks a lot

**Comment by noman55** [comment]
@sean-k1 can you look into this pls?

**Comment by sean-k1** [comment]
@noman55 
You have two choices
First, if you're using mysql 8 and you're still using 0.25, I don't think you need DDL tracing. 
In that case, you can use version 0.45.1. 

Second, if you are using mysql 8 and you need DDL tracing, you can use the 
set binlog_row_metadata='FULL' , binlog_row_image='FULL' and then set 
1.0.9 should work.

If you don't want to set these global variables, you can proceed with the first case
